### ISSUE TITLE
Docker installation?

### ISSUE THREAD

**Issue by drmetro09** [iamarunbrahma/vision-parse#3]
It would be very helpful if we get to install this tool in docker using docker compose .

Thanks

**Comment by iamarunbrahma** [comment]
Added support for docker installation. (If you use local models, increase the memory limit as per model size).

Set a MODEL_NAME environment variable (it's required). If you are using the OpenAI model, set OPENAI_API_KEY. If you are using the Gemini model, set GEMINI_API_KEY.

**Comment by drmetro09** [comment]
> Added support for docker installation. (If you use local models, increase the memory limit as per model size).
> 
> Set a MODEL_NAME environment variable (it's required). If you are using the OpenAI model, set OPENAI_API_KEY. If you are using the Gemini model, set GEMINI_API_KEY.

Can we use nvidia gpu ?

**Comment by iamarunbrahma** [comment]
yes, you can. If you have GPU's, uncomment these lines in docker-compose.yml:

devices:
     - driver: nvidia
        count: all
        capabilities: [gpu]

**Comment by drmetro09** [comment]
# if i want to use llama 3.2 vision:11b where should i put the name ? Can you edit the below docker compose yml and put the name ? So i can know where to put the name
/name: vision-parse

services:
  vision-parse:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MODEL_NAME=${MODEL_NAME:?MODEL_NAME is required}
    environment:
      - MODEL_NAME=${MODEL_NAME:?MODEL_NAME is required}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}  # Optional: For OpenAI models
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}  # Optional: For Gemini models
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "11434:11434"  # Expose Ollama port
    deploy:
      resources:
        limits:
          memory: 16G  # Set memory limit to 16GB
        reservations:
          memory: 8G   # Guarantee at least 8GB
          # Uncomment below lines if you have NVIDIA GPU available
          # devices:
          #   - driver: nvidia
          #     count: all
          #     capabilities: [gpu]
    command: tail -f /dev/null  # Keep container running

**Comment by drmetro09** [comment]
And i already have a locally hosted ollama docker container running how do i use that in this container of vision parse?

**Comment by iamarunbrahma** [comment]
1. To use llama3.2-vision:11b, you don't put it directly in the docker-compose.yml. Instead, you set it as an environment variable when running docker-compose. Here's how:

```bash
export MODEL_NAME=llama3.2-vision:11b

docker-compose down && docker-compose build && docker-compose up -d
```

2. This DockerFIle will automatically download and setup Ollama within vision-parse docker container, if you use any of the locally hosted models such as llama3.2-vision:11b. You can actually check it by first executing an interactive shell and then run `ollama list` or `ollama ps`:

```bash
docker-compose exec vision-parse bash

ollama list
```

**Comment by drmetro09** [comment]
I use unraid , so its difficult for me to setup this , also it doesn’t have gui to work i tired to install but doesnt work
