### ISSUE TITLE
[FEATURE]: specify the URL for the Ollama connection

### ISSUE THREAD

**Issue by marcelocecin** [iamarunbrahma/vision-parse#6]
### Problem Statement

Hi
Would it be possible to specify the [URL for the Ollama connection](https://github.com/PipedreamHQ/pipedream/blob/master/components/ollama/ollama.app.mjs)?
My idea is to use the library within [Pipedream](https://pipedream.com/docs/code/python) and run LLM on my Mac
Thanks

### Proposed Solution

```python
from vision_parse import VisionParser

# Initialize parser
parser = VisionParser(
    model_name="llama3.2-vision:11b", # For local models, you don't need to provide the api key
    ollama_url="https://example123.ngrok-free.app"
    temperature=0.4,
    top_p=0.3,
    extraction_complexity=False # Set to True for more detailed extraction
)

# Convert PDF to markdown
pdf_path = "path/to/your/document.pdf"
markdown_pages = parser.convert_pdf(pdf_path)

# Process results
for i, page_content in enumerate(markdown_pages):
    print(f"\n--- Page {i+1} ---\n{page_content}")
```

### Final Checklist

- [X] This feature would be useful to other users
- [ ] I'm willing to help implement this feature

**Comment by iamarunbrahma** [comment]
Hello @marcelocecin , you can set ollama URL by passing a value through ollama_config:

```python
from vision_parse import VisionParser

# Initialize parser with Ollama configuration
parser = VisionParser(
    model_name="llama3.2-vision:11b",
    temperature=0.5,
    top_p=0.3,
    detailed_extraction=True,
    ollama_config={
        "OLLAMA_HOST": "https://example123.ngrok-free.app",
    },
)
 ```
 
 Note: In the current update, I have changed the parameter name from `extraction_complexity` to `detailed_extraction`
